ALTER TABLE subjects
    ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP NULL AFTER updated_at;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS phone VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS department VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS bio TEXT NULL;
